services:
  db:
    image: postgres:17-alpine
    container_name: deadpigeons_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: deadpigeons_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/dataccess/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql

volumes:
  postgres_data:
